
all:
	node sch.js > project.net
	cat project.net

clean:
	rm -f *.net

setup:
	mkdir -p tmp
	echo download MRS_Toolchain_Linux_
	firefox https://www.mounriver.com/download
#	curl --output tmp/wch_toolchain.tar.xz https://file-oss.mounriver.com/tools/MRS_Toolchain_Linux_x64_V210.tar.xz


